version: '2'
services:
  web:
    container_name: mon-espace-collectivite
#    image: mec:0.1.0
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    ports:
      - "3000:8088"
    environment:
      PORT: 8088
      DATABASE_URL: postgres://h@localhost/mec
