version: 2.1

orbs:
  skip: theodo/skip@0.1.2
#  browser-tools: circleci/browser-tools@1.4.0
#  cypress: cypress-io/cypress@1
executors:
  node:
    docker:
      - image: cimg/node:19.3.0
        environment:
          TZ: 'UTC'
  e2e:
    docker:
      - image: cimg/node:19.3.0-browsers
        environment:
          TZ: 'UTC'

parameters:
  cache_version:
    type: string
    default: '20221226-01'
  virtual_store_dir:
    type: string
    default: './.pnpm'
  lockfile:
    type: string
    default: './pnpm-lock.yaml'
  registry:
    type: string
    default: rg.fr-par.scw.cloud/mec-web
  image:
    type: string
    default: mec-web-<< pipeline.git.branch >> | sed -e 's/\//-/g'
  build_version:
    type: string
    default: $CIRCLE_SHA1
  deploy_version:
    type: string
    default: latest
  e2e_version:
    type: string
    default: e2e

workflows:
  version: 2
  lint_test_build_deploy:
    jobs:
      - prepare_dependencies
      - lint_and_test:
          requires:
            - prepare_dependencies
      - build_web:
          requires:
            - prepare_dependencies
      - chromatic:
          requires:
            - prepare_dependencies
      - test_e2e:
          requires:
            - build_web
      - deploy_web:
          requires:
            - lint_and_test
            - chromatic
            - test_e2e

jobs:
  prepare_dependencies:
    executor: node
    resource_class: large
    steps:
      - checkout
      - install_dependencies
      - run:
          name: 'Fetch dependencies'
          command: pnpm install --virtual-store-dir << pipeline.parameters.virtual_store_dir >>
      - save_cache:
          key: << pipeline.parameters.cache_version >>-pnpm-{{ checksum "<< pipeline.parameters.lockfile >>" }}
          paths:
            - << pipeline.parameters.virtual_store_dir >>
            - ./node_modules
            - ./apps/web/node_modules
            - ./apps/ci/node_modules
            - ./packages/e2e/node_modules
            - ./packages/cdk/node_modules

  lint_and_test:
    executor: node
    resource_class: large
    steps:
      - checkout
      - install_dependencies
      - run:
          name: 'Lint'
          command: pnpm lint
      - run:
          name: 'Prisma generate'
          command: pnpm -F @mec/web prisma:generate
      - run:
          name: 'Tsc'
          command: pnpm tsc
      - run:
          name: 'Test @mec/web'
          command: pnpm -F @mec/web test

  build_web:
    executor: node
    resource_class: large
    steps:
      - checkout
      - setup_docker_env
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: 'Build docker image'
          command: docker build -t $IMAGE_BUILD_TAG -f docker/web/Dockerfile .
      - run:
          name: 'Login to registry and push image'
          command: |
            docker login $REGISTRY -u nologin --password-stdin \<<< "$SCW_SECRET_KEY"
            docker push $IMAGE_BUILD_TAG

  chromatic:
    executor: node
    resource_class: large
    steps:
      - checkout
      - install_dependencies
      - run:
          name: 'Setup DSFR'
          command: pnpm -F @mec/web setup:dsfr
      - run:
          name: 'Build storybook and test components'
          command: pnpm -F @mec/web chromatic

  test_e2e:
    executor: e2e
    resource_class: large
    parallelism: 1
    steps:
      - checkout
      - install_dependencies
      - setup_docker_env
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: 'Login to registry and pull image'
          command: |
            docker login $REGISTRY -u nologin --password-stdin \<<< "$SCW_SECRET_KEY"
            docker pull $IMAGE_BUILD_TAG
      - run:
          name: 'Install playwright'
          command: |
            cd packages/e2e
            sudo pnpx playwright install-deps
            pnpx playwright install
      #      - run:
      #          name: 'Up docker-compose'
      #          command: |
      #            docker-compose -f docker/web/docker-compose.ci.yml up
      - run:
          name: 'Run playwright'
          command: |
            SHARD="$((${CIRCLE_NODE_INDEX}+1))"
            pnpm -F @mec/e2e playwright test --shard=${SHARD}/${CIRCLE_NODE_TOTAL}

  deploy_web:
    executor: node
    resource_class: large
    steps:
      - checkout
      - setup_docker_env
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: 'Login to registry and push image'
          command: |
            docker login $REGISTRY -u nologin --password-stdin \<<< "$SCW_SECRET_KEY"
            docker pull $IMAGE_BUILD_TAG
            docker tag $IMAGE_BUILD_TAG $IMAGE_DEPLOY_TAG
            docker push $IMAGE_DEPLOY_TAG
      - run:
          name: 'Deploy image'
          command: |
            echo "TODO"

commands:

  install_pnpm:
    steps:
      - run:
          name: 'Install pnpm'
          command: sudo corepack enable && corepack prepare pnpm@latest --activate

  install_dependencies:
    steps:
      - install_pnpm
      - restore_cache:
          keys:
            - << pipeline.parameters.cache_version >>-pnpm-{{ checksum "<< pipeline.parameters.lockfile >>" }}

  setup_docker_env:
    steps:
      - run:
          name: "Set docker env vars"
          command: |
            echo "export REGISTRY=<< pipeline.parameters.registry >>" >> ${BASH_ENV}
            echo "export IMAGE_NAME=$(echo 'mec-web-<< pipeline.git.branch >>' | sed -e 's/\//-/g')" >> ${BASH_ENV}
            echo "export IMAGE_BUILD_TAG=$(echo '<< pipeline.parameters.registry >>/$IMAGE_NAME:<< pipeline.parameters.build_version >>')" >> ${BASH_ENV}
            echo "export IMAGE_DEPLOY_TAG=$(echo '<< pipeline.parameters.registry >>/$IMAGE_NAME:<< pipeline.parameters.deploy_version >>')" >> ${BASH_ENV}
            echo "export IMAGE_E2E_TAG=$(echo '<< pipeline.parameters.registry >>/$IMAGE_NAME:<< pipeline.parameters.e2e_version >>')" >> ${BASH_ENV}
