version: 2.1

# Circle CI retro public key for ssh access
# ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFMqZkFRArBl66kbkXuFi16ccYwlMSRtyFcBiCXarmLX retro@circleci.com

orbs:
  skip: theodo/skip@0.1.2
#  browser-tools: circleci/browser-tools@1.4.0
#  cypress: cypress-io/cypress@1
executors:
  node:
    docker:
      - image: cimg/node:19.3.0
        environment:
          TZ: 'UTC'
  node-browsers:
    docker:
      - image: cimg/node:19.3.0-browsers
        environment:
          TZ: 'UTC'

parameters:
  cache_version:
    type: string
    default: '20221226-01'
  virtual_store_dir:
    type: string
    default: './.pnpm'
  lockfile:
    type: string
    default: './pnpm-lock.yaml'

commands:
  wip-fail:
    steps:
      - run:
          name: 'WIP - Fail job'
          command: /bin/false

  install-pnpm:
    steps:
      - run:
          name: 'Install pnpm'
#           command: curl -L https://pnpm.js.org/pnpm.js | node - add --global pnpm@7
          command: sudo corepack enable && corepack prepare pnpm@latest --activate

  fetch-dependencies:
    parameters:
      cache_key:
        type: string
        default: 'pnpm'
    steps:
      - install-pnpm
      - restore_cache:
          keys:
            - << pipeline.parameters.cache_version >>-<< parameters.cache_key >>-{{ checksum "<< pipeline.parameters.lockfile >>" }}
            # Get previous dependencies to speed up download
            # - << parameters.cache_version >>-<< parameters.cache_key >>-
      - run:
          name: 'Fetch dependencies'
          command: pnpm install --virtual-store-dir << pipeline.parameters.virtual_store_dir >>
      - save_cache:
          key: << pipeline.parameters.cache_version >>-<< parameters.cache_key >>-{{ checksum "<< pipeline.parameters.lockfile >>" }}
          paths:
            - << pipeline.parameters.virtual_store_dir >>
            - ./node_modules
            - ./apps/web/node_modules
            - ./apps/ci/node_modules
            - ./packages/e2e/node_modules
            - ./packages/cdk/node_modules

  install-dependencies:
    parameters:
      cache_key:
        type: string
        default: 'pnpm'
    steps:
      - install-pnpm
      - restore_cache:
          keys:
            - << pipeline.parameters.cache_version >>-<< parameters.cache_key >>-{{ checksum "<< pipeline.parameters.lockfile >>" }}

  lint:
    steps:
      - run:
          name: 'Lint'
          command: pnpm lint
      - run:
          name: 'Prisma generate'
          command: pnpm -F @mec/web prisma:generate
      - run:
          name: 'Tsc'
          command: pnpm tsc
      - run:
          name: 'Test @mec/web'
          command: pnpm -F @mec/web test


  build-web:
    parameters:
      registry:
        type: string
        default: rg.fr-par.scw.cloud/mec-web
      image:
        type: string
        default: mec-web-<< pipeline.git.branch >> | sed -e 's/\//-/g'
      version:
        type: string
        default: latest
    steps:
      - setup_remote_docker
      - run:
          name: "Set env vars"
          command: |
            echo "export IMAGE_NAME=$(echo 'mec-web-<< pipeline.git.branch >>' | sed -e 's/\//-/g')" >> ${BASH_ENV}
            echo "export TEST_BRANCH=<<pipeline.git.branch>>" >> ${BASH_ENV}
      - run:
          name: 'Debug tag'
          command: echo $IMAGE_NAME
      - run:
          name: 'Login to registry'
          command: docker login << parameters.registry >> -u nologin --password-stdin \<<< "$SCW_SECRET_KEY"
      - run:
          name: 'Build docker image'
          command: docker build -t << parameters.registry >>/$IMAGE_NAME:<< parameters.version >> -f docker/web/Dockerfile .
#      - run:
#          name: 'Push image'
#          command: docker push << parameters.image >>:<< parameters.version >>


jobs:
  prepare_dependencies:
    executor: node
    resource_class: large
    steps:
      - checkout
      - fetch-dependencies

  lint_and_test:
    executor: node
    resource_class: large
    steps:
      - checkout
      - install-dependencies
      - lint

  build_web:
    executor: node
    resource_class: large
    steps:
      - checkout
      - build-web

workflows:
  version: 2
  ci-pipeline:
    jobs:
      - prepare_dependencies
      - lint_and_test:
          requires:
            - prepare_dependencies
      - build_web:
          requires:
            - prepare_dependencies
#      - build_storybook:
#          requires:
#            - prepare_dependencies
#      - test_e2e:
#          requires:
#            - build_web
#      - deploy_chromatic:
#          requires:
#            - lint_and_test
#            - build_storybook
#      - deploy_web:
#          required:
#            - lint_and_test
#            - test_e2e
