name: '🎨 Chromatic'

on:
  - push

jobs:
  publish:
    name: 🚀 Build storybook and publish
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: yarn install --ignore-engines --frozen-lockfile

      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          buildScriptName: build:storybook
          workingDir: apps/web
